series: Ray Tracers
title: Basic Ray Tracer
author:
  name: Brockton Roth
  email: 
  github: https://github.com/IGME-RIT
description: Demonstration of a basic ray tracing algorithm.
language: C++
tags:
  - Graphics
  - Math
extra_resources:
  - "https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.1.-Ray-tracing-with-OpenGL-Compute-Shaders-(Part-I)"
connections:
  - series: Basic OpenGL with GLFW
    title: Drawing a Cube